FROM node:22.0.0-alpine as build-deps
WORKDIR /app
COPY package.json package.json
RUN npm install --legacy-peer-deps

FROM node:22-alpine as builder
WORKDIR /app
COPY --from=build-deps /app/node_modules ./node_modules
COPY . .
RUN npm run build -- --configuration=production

FROM nginx:1.23.3
EXPOSE 80
COPY --from=builder /app/dist/portal-admin /usr/share/nginx/html
RUN rm etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx","-g","daemon off;"]

